### ISSUE TITLE
Help menu doesn't show full text

### ISSUE THREAD

**Issue by grimnight** [erik/vxsv#1]
When accessing the help menu `?`, it only show until "row makes the comparison evaluate to true.".

**Comment by erik** [comment]
The help page should be scrollable with arrow keys or <kbd>j</kbd>/<kbd>k</kbd>. Is that not working for you?

**Comment by grimnight** [comment]
I can scroll it just fine, with arrow keys, with j/k and with mouse wheel, but it stops at `row makes the comparison evaluate to true.`. It doesn't go any futher.

**Comment by erik** [comment]
Strange, seems to work fine for me. Could you give some more details of your environment?

**Comment by grimnight** [comment]
Ubuntu, go version go1.20.2 linux/amd64. What other info do you need?

**Comment by erik** [comment]
Thanks, I was able to reproduce it by shrinking my terminal vertically. Must be a bug in the popup scroll handler https://github.com/erik/vxsv/blob/master/handler.go#L614

**Comment by erik** [comment]
Fixed! Thanks for the heads up
